# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XjQ6kMSnzG8AetzOtxETmgvjg2ZPnugb
"""

print("i am going college for \nlearning nlp")

print("i am going \ncollege for \nlearning nlp")

"""###space - \t"""

print("i am going \ncollege for \tlearning nlp")

"""###carriage return(\r)"""

print("i am going college for \rlearning nlp")

import re

string="007 james bond wants to learn the python"
pattern=r'\d+'
matching=re.match(pattern,string)
matching.group()

"""re.search()"""

import re
pattern = r'\d+'
string = 'james bond 007 wants 008 to learn the python'
matching = re.search(pattern, string)
matching.group()

"""###re.findall()"""

import re
pattern = r'\d+'
string = 'james bond 007 wants 008 to learn67 the python'
matching = re.findall(pattern, string)
matching

import re
pattern = r'\d'
string = 'james bond 007 wants 008 to learn67 the python'
matching = re.sub(pattern,'#',string)
matching

import re
pattern = r'\d'
string = 'james bond ### wants # to learn#7 the python'
matching = re.sub(pattern,' ',string)
matching

"""Problem: NLP Text Cleaning and Extraction

You are tasked with cleaning a text dataset to prepare it for NLP tasks. Your goal is to:

Extract all email addresses from the text. Remove all numbers (to prevent numeric features from skewing the NLP analysis). Extract all hashtags (for sentiment analysis and trending topics). Normalize whitespace to ensure there's no extra spaces between words. Remove any HTML tags that may be included in the text (from web scraping).
"""

# Test case
text = """
Hello world! Contact us at info@example.com or support123@company.org. Follow us on social media: #AI #MachineLearning.
Visit <a href="http://example.com">our website</a> for more details. This is a test with number 1234.
"""

pattern=r'[a-zA-Z0-9._%+-]+@+[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}'
emails=re.findall(pattern,text)
emails

pattern=r'#\w+'
hash_tagfs=re.findall(pattern,text)
hash_tagfs

